/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.employee.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Dummy service. Represents a row in the &quot;Company_Dummy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.employee.service.model.impl.DummyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.employee.service.model.impl.DummyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Dummy
 * @generated
 */
@ProviderType
public interface DummyModel extends BaseModel<Dummy>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dummy model instance should use the {@link Dummy} interface instead.
	 */

	/**
	 * Returns the primary key of this dummy.
	 *
	 * @return the primary key of this dummy
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dummy.
	 *
	 * @param primaryKey the primary key of this dummy
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this dummy.
	 *
	 * @return the uuid of this dummy
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this dummy.
	 *
	 * @param uuid the uuid of this dummy
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the company emp ID of this dummy.
	 *
	 * @return the company emp ID of this dummy
	 */
	public long getCompanyEmpId();

	/**
	 * Sets the company emp ID of this dummy.
	 *
	 * @param companyEmpId the company emp ID of this dummy
	 */
	public void setCompanyEmpId(long companyEmpId);

	/**
	 * Returns the group ID of this dummy.
	 *
	 * @return the group ID of this dummy
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dummy.
	 *
	 * @param groupId the group ID of this dummy
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dummy.
	 *
	 * @return the company ID of this dummy
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dummy.
	 *
	 * @param companyId the company ID of this dummy
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the emp first name of this dummy.
	 *
	 * @return the emp first name of this dummy
	 */
	@AutoEscape
	public String getEmpFirstName();

	/**
	 * Sets the emp first name of this dummy.
	 *
	 * @param empFirstName the emp first name of this dummy
	 */
	public void setEmpFirstName(String empFirstName);

	/**
	 * Returns the emp last name of this dummy.
	 *
	 * @return the emp last name of this dummy
	 */
	@AutoEscape
	public String getEmpLastName();

	/**
	 * Sets the emp last name of this dummy.
	 *
	 * @param empLastName the emp last name of this dummy
	 */
	public void setEmpLastName(String empLastName);

	/**
	 * Returns the email of this dummy.
	 *
	 * @return the email of this dummy
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this dummy.
	 *
	 * @param email the email of this dummy
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this dummy.
	 *
	 * @return the phone of this dummy
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this dummy.
	 *
	 * @param phone the phone of this dummy
	 */
	public void setPhone(String phone);

	/**
	 * Returns the company name of this dummy.
	 *
	 * @return the company name of this dummy
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this dummy.
	 *
	 * @param companyName the company name of this dummy
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the prof image ID of this dummy.
	 *
	 * @return the prof image ID of this dummy
	 */
	public long getProfImageId();

	/**
	 * Sets the prof image ID of this dummy.
	 *
	 * @param profImageId the prof image ID of this dummy
	 */
	public void setProfImageId(long profImageId);

	/**
	 * Returns the create date of this dummy.
	 *
	 * @return the create date of this dummy
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dummy.
	 *
	 * @param createDate the create date of this dummy
	 */
	public void setCreateDate(Date createDate);

	@Override
	public Dummy cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}