/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.employee.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;Company_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.employee.service.model.impl.EmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.employee.service.model.impl.EmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @generated
 */
@ProviderType
public interface EmployeeModel extends BaseModel<Employee>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee.
	 *
	 * @return the uuid of this employee
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this employee.
	 *
	 * @param uuid the uuid of this employee
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the company emp ID of this employee.
	 *
	 * @return the company emp ID of this employee
	 */
	public long getCompanyEmpId();

	/**
	 * Sets the company emp ID of this employee.
	 *
	 * @param companyEmpId the company emp ID of this employee
	 */
	public void setCompanyEmpId(long companyEmpId);

	/**
	 * Returns the group ID of this employee.
	 *
	 * @return the group ID of this employee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee.
	 *
	 * @param groupId the group ID of this employee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee.
	 *
	 * @return the company ID of this employee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee.
	 *
	 * @param companyId the company ID of this employee
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the emp first name of this employee.
	 *
	 * @return the emp first name of this employee
	 */
	@AutoEscape
	public String getEmpFirstName();

	/**
	 * Sets the emp first name of this employee.
	 *
	 * @param empFirstName the emp first name of this employee
	 */
	public void setEmpFirstName(String empFirstName);

	/**
	 * Returns the emp last name of this employee.
	 *
	 * @return the emp last name of this employee
	 */
	@AutoEscape
	public String getEmpLastName();

	/**
	 * Sets the emp last name of this employee.
	 *
	 * @param empLastName the emp last name of this employee
	 */
	public void setEmpLastName(String empLastName);

	/**
	 * Returns the email of this employee.
	 *
	 * @return the email of this employee
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this employee.
	 *
	 * @param email the email of this employee
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this employee.
	 *
	 * @return the phone of this employee
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this employee.
	 *
	 * @param phone the phone of this employee
	 */
	public void setPhone(String phone);

	/**
	 * Returns the company name of this employee.
	 *
	 * @return the company name of this employee
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this employee.
	 *
	 * @param companyName the company name of this employee
	 */
	public void setCompanyName(String companyName);

	/**
	 * Returns the prof image ID of this employee.
	 *
	 * @return the prof image ID of this employee
	 */
	public long getProfImageId();

	/**
	 * Sets the prof image ID of this employee.
	 *
	 * @param profImageId the prof image ID of this employee
	 */
	public void setProfImageId(long profImageId);

	/**
	 * Returns the create date of this employee.
	 *
	 * @return the create date of this employee
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee.
	 *
	 * @param createDate the create date of this employee
	 */
	public void setCreateDate(Date createDate);

	@Override
	public Employee cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}