/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.custom.object.service.model.impl;

import com.liferay.custom.object.service.model.StateObject;
import com.liferay.custom.object.service.service.StateObjectLocalServiceUtil;

/**
 * The extended model base implementation for the StateObject service. Represents a row in the &quot;customObjService_StateObject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StateObjectImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StateObjectImpl
 * @see StateObject
 * @generated
 */
public abstract class StateObjectBaseImpl
	extends StateObjectModelImpl implements StateObject {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a state object model instance should use the <code>StateObject</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			StateObjectLocalServiceUtil.addStateObject(this);
		}
		else {
			StateObjectLocalServiceUtil.updateStateObject(this);
		}
	}

}