info:
    description: "HeadlessDocumentUpload REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "HeadlessDocumentUpload"
    version: v1.0
openapi: 3.0.1

components:
    schemas:
        SuccessResponse:
            type: object
            properties:
                message:
                    type: string
                    example: "File uploaded successfully"

paths:

    "/documents":
        post:
            operationId: postDocument
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            properties:
                                breadcrumb:
                                    type: string
                                file:
                                    format: binary
                                    type: string
                            type: object
            responses:
                200:
                    description: Success!
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'

                        application/xml:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'
            tags: [StaffConnectDocument]

        put:
            operationId: putDocument
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            properties:
                                breadcrumb:
                                    type: string
                                file:
                                    format: binary
                                    type: string
                            type: object
            responses:
                200:
                    description: Success!
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'

                        application/xml:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'
            tags: [StaffConnectDocument]

        delete:
            operationId: deleteDocument
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            properties:
                                breadcrumb:
                                    type: string
                                file:
                                    type: string
                            type: object
            responses:
                200:
                    description: Success!
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'

                        application/xml:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'
            tags: [StaffConnectDocument]