info:
    description: "PromotionEndpoints REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "PromotionEndpoints"
    version: v1.0
openapi: 3.0.1

components:
    schemas:
        PromotionCategory:
            type: object
            properties:
                name:
                    type: string
                categoryId:
                    format: int64
                    type: integer
                desc:
                    type: string
                superCategoryId:
                    type: number
                subCategoriesIds:
                    type: array
                    items:
                        format: int64
                        type: integer
                hasSubCategories:
                    type: boolean

        ValidateCategorySelectionRequest:
            type: object
            properties:
                rootCategory:
                    format: int64
                    type: integer
                firstCategory:
                    format: int64
                    type: integer
                secondCategory:
                    format: int64
                    type: integer
                thirdCategory:
                    format: int64
                    type: integer
                fourthCategory:
                    format: int64
                    type: integer

        ValidateCategorySelectionResponse:
            type: object
            properties:
                isValid:
                    type: boolean




paths:
    "/getPromotionCategoriesByName/{categoryName}/{groupId}":
        get:
            parameters:
                - in: path
                  name: categoryName
                  required: true
                  schema:
                      type: string
                - in: path
                  name: groupId
                  required: true
                  schema:
                      format: int64
                      type: integer

            responses:
                '200':
                    description: Success!
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: '#/components/schemas/PromotionCategory'
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: '#/components/schemas/PromotionCategory'
                                type: array

            tags: [PromotionCategory]

    "/getPromotionCategoryById/{categoryId}":
        get:
            parameters:
                - in: path
                  name: categoryId
                  required: true
                  schema:
                      format: int64
                      type: integer


            responses:
                '200':
                    description: Success!
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PromotionCategory'

                        application/xml:
                            schema:
                                $ref: '#/components/schemas/PromotionCategory'
            tags: [PromotionCategory]

    "/getPromotionSubCategoriesById/{categoryId}":
        get:
            parameters:
                - in: path
                  name: categoryId
                  required: true
                  schema:
                      format: int64
                      type: integer


            responses:
                '200':
                    description: Success!
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: '#/components/schemas/PromotionCategory'
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: '#/components/schemas/PromotionCategory'
                                type: array

            tags: [PromotionCategory]

    "/validatePromotionCategory":
        post:
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            $ref: '#/components/schemas/ValidateCategorySelectionRequest'


            responses:
                200:
                    description: Success!
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ValidateCategorySelectionResponse'

                        application/xml:
                            schema:
                                $ref: '#/components/schemas/ValidateCategorySelectionResponse'



            tags: [ValidateCategorySelection]
